// <auto-generated />
namespace Examination.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v201 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v201));
        
        string IMigrationMetadata.Id
        {
            get { return "201707030914016_v2.0.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
